FROM node

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

RUN touch ./config/apikey.js

EXPOSE 8080
CMD [ "npm", "start" ]

# Generated by Cloud66 Starter

# FROM node

# ENV APP_HOME /app
# RUN mkdir -pv $APP_HOME
# WORKDIR $APP_HOME

# ADD . $APP_HOME

# ENV NODE_ENV production
# ENV NPM_CONFIG_LOGLEVEL warn

# ADD CUSTOM REGISTRY HERE IF REQUIRED
# ENV CUSTOM_REGISTRY https://registry.npmjs.org/ 
# RUN npm config set strict-ssl false
# RUN npm config set registry $CUSTOM_REGISTRY

# RUN npm install
